baseURL = "https://example.com/"
languageCode = "en-us"
title = "संस्कारे विश्वासटिप्पन्यः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/sanskrit-coders/sanskrit-documentation-theme-hugo/edit/master/exampleSite/content/"
  contactLink = "https://github.com/sanskrit-coders/sanskrit-documentation-theme-hugo/issues/new"
  env = "production"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ''
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  style = 'friendly'
  tabWidth = 2
